{{- if not .Values.secrets.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "latr.fullname" . }}
  labels:
    {{- include "latr.labels" . | nindent 4 }}
type: Opaque
stringData:
  linode-token: {{ .Values.secrets.linodeToken | quote }}
  vault-role-id: {{ .Values.secrets.vaultRoleId | quote }}
  vault-secret-id: {{ .Values.secrets.vaultSecretId | quote }}
{{- end }}
